# Generated by Django 6.0.1 on 2026-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
