# Generated by Django 6.0.1 on 2026-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='weakness',
            field=models.ManyToManyField(related_name='enemies', to='common.role'),
        ),
    ]
