# Generated by Django 6.0.1 on 2026-03-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_enemycardtheme_enemy_and_more'),
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='card_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemies', to='cards.card'),
        ),
    ]
