# Generated by Django 6.0.1 on 2026-03-31 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('first_win', 'First Win'), ('win_streak', 'Win Streak'), ('total_wins', 'Total Wins'), ('total_battles', 'Total Battles'), ('perfect_victory', 'Perfect Victory'), ('perfect_lose', 'Perfect Lose'), ('first_lose', 'First Lose'), ('total_loses', 'Total Loses'), ('first_character_creation', 'First Character Creation'), ('first_partner_creation', 'First Partner Creation'), ('first_enemy_creation', 'First Enemy Creation'), ('first_card_creation', 'First Card Creation')], max_length=100)),
                ('threshold', models.IntegerField(default=1)),
                ('icon', models.CharField(default='🏆', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
