# Generated by Django 6.0.1 on 2026-03-31 19:13

from django.db import migrations

ACHIEVEMENTS = [

{ 'name': 'First Blood',     'description': 'Win your first battle',          'type': 'first_win',        'threshold': 1,  'icon': '⚔️'  },
    { 'name': 'On a Roll',       'description': 'Win 3 battles in a row',          'type': 'win_streak',       'threshold': 3,  'icon': '🔥'  },
    { 'name': 'Unstoppable',     'description': 'Win 10 battles in a row',         'type': 'win_streak',       'threshold': 10, 'icon': '💀'  },
    { 'name': 'Veteran',         'description': 'Win 3 battles total',            'type': 'total_wins',       'threshold': 3, 'icon': '🏆'  },
    { 'name': 'Champion',        'description': 'Win 5 battles total',            'type': 'total_wins',       'threshold': 5, 'icon': '👑'  },
    { 'name': 'Battle Hardened', 'description': 'Play 2 battles',                 'type': 'total_battles',    'threshold': 2, 'icon': '🛡️'  },
    { 'name': 'Untouchable',     'description': 'Win a battle with full hp',  'type': 'perfect_victory', 'threshold': 1,  'icon': '✨'  },
{ 'name': 'Newbie',     'description': 'Lose a battle to an enemy with full hp',  'type': 'perfect_lose', 'threshold': 1,  'icon': '✨'  },
{ 'name': 'Total Loser',     'description': 'Lose a battle to an enemy with full hp 3 times',  'type': 'perfect_lose', 'threshold': 3,  'icon': '✨'  },
{ 'name': 'You tried',     'description': 'Lose your first battle',  'type': 'first_lose', 'threshold': 1,  'icon': '💀'  },
{ 'name': 'Losing Often',     'description': 'Lose 3 battles',  'type': 'total_loses', 'threshold': 3,  'icon': '💀'  },
{ 'name': 'Losing Enjoyer',     'description': 'Lose 5 battles',  'type': 'total_loses', 'threshold': 5,  'icon': '💀'  },
{ 'name': 'Character Creator',     'description': 'Create your first character',  'type': 'first_character_creation', 'threshold': 1,  'icon': '🔥'  },
{ 'name': 'Partner Creator',     'description': 'Create your first partner',  'type': 'first_partner_creation', 'threshold': 1,  'icon': '🔥'  },
{ 'name': 'Enemy Creator',     'description': 'Create your first enemy',  'type': 'first_enemy_creation', 'threshold': 1,  'icon': '🔥'  },
{ 'name': 'Card Creator',     'description': 'Create your first card',  'type': 'first_card_creation', 'threshold': 1,  'icon': '🔥'  },
# { 'name': 'Battle Demon',     'description': 'Win 3 battles with full hp',  'type': 'perfect_victory', 'threshold': 3,  'icon': '✨'  },

]

def seed_achievements(apps, schema_editor):
    Achievement = apps.get_model('achievements', 'Achievement')
    for a in ACHIEVEMENTS:
        Achievement.objects.get_or_create(type=a['type'],threshold=a['threshold'], defaults=a)



class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [migrations.RunPython(seed_achievements, migrations.RunPython.noop)]
