
from .base import *

DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = [host for host in (os.getenv('ALLOWED_HOSTS') or "").split(',') if host]



STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = 'django-db'


EMAIL_BACKEND = 'CreatorApp.azure_email_backend.AzureCommunicationEmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

CSRF_TRUSTED_ORIGINS = [f"https://{os.getenv('AZURE_APP_HOSTNAME','')}"]
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_SAMESITE = 'Lax'
#
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_HTTPONLY = True
#
# X_FRAME_OPTIONS = 'DENY'
#
# SECURE_CONTENT_TYPE_NOSNIFF = True
#
# SECURE_BROWSER_XSS_FILTER = True