# Generated by Django 6.0.1 on 2026-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('ALIEN', 'ALIEN'), ('HERO', 'HERO'), ('GOD', 'GOD'), ('DEMON', 'DEMON'), ('TIME_TRAVELER', 'TIME TRAVELER'), ('VILLAIN', 'VILLAIN'), ('ANGEL', 'ANGEL'), ('OTHER', 'OTHER')], default='OTHER')),
                ('power', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('roles', models.ManyToManyField(related_name='characters', to='common.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
