# Generated by Django 6.0.1 on 2026-03-28 09:13

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_create_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attack', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('defense', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('hp', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('ALIEN', 'ALIEN'), ('HERO', 'HERO'), ('GOD', 'GOD'), ('DEMON', 'DEMON'), ('TIME TRAVELER', 'TIME TRAVELER'), ('VILLAIN', 'VILLAIN'), ('ANGEL', 'ANGEL'), ('OTHER', 'OTHER')], default='OTHER')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(related_name='characters', to='common.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
