# Generated by Django 6.0.1 on 2026-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='power',
            new_name='defense',
        ),
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('ALIEN', 'ALIEN'), ('HERO', 'HERO'), ('GOD', 'GOD'), ('DEMON', 'DEMON'), ('TIME TRAVELER', 'TIME TRAVELER'), ('VILLAIN', 'VILLAIN'), ('ANGEL', 'ANGEL'), ('OTHER', 'OTHER')], default='OTHER'),
        ),
    ]
