# Generated by Django 6.0.1 on 2026-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
