# Generated by Django 6.0.1 on 2026-02-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_rename_power_character_defense_character_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='defense',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
