# Generated by Django 6.0.1 on 2026-03-27 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
