# Generated by Django 6.0.1 on 2026-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ATTACK', 'ATTACK'), ('DEFEND', 'DEFEND'), ('HEAL', 'HEAL'), ('BUFF', 'BUFF'), ('SUPPORT', 'SUPPORT'), ('SEARCH', 'SEARCH')], max_length=20, unique=True)),
            ],
        ),
    ]
