# Generated by Django 6.0.1 on 2026-03-26 12:49

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    moderator, _ = Group.objects.get_or_create(name='Moderator')
    moderator_permissions = Permission.objects.filter(codename__in=[
        'add_character','change_character','delete_character','view_character','add_partner','change_partner','delete_partner',
        'view_partner','add_enemy','change_enemy','delete_enemy','view_enemy'
    ])

    moderator.permissions.set(moderator_permissions)

    battle_manager, _ = Group.objects.get_or_create(name='BattleManager')
    battle_manager_permissions = Permission.objects.filter(codename__in=[
        'add_battle','change_battle','delete_battle','view_battle','add_battlelog','change_battlelog',
        'delete_battlelog','view_battlelog'
    ])

    battle_manager.permissions.set(battle_manager_permissions)

def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=["Moderator","BattleManager"]).delete()





class Migration(migrations.Migration):


    dependencies = [
        ('common', '0002_seed_roles'),
    ]

    operations = [
        migrations.RunPython(create_groups,delete_groups),
    ]
