# Generated by Django 6.0.1 on 2026-03-27 10:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
