# Generated by Django 6.0.1 on 2026-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbattlestats',
            name='lose_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbattlestats',
            name='win_streak',
            field=models.IntegerField(default=0),
        ),
    ]
