# Generated by Django 6.0.1 on 2026-03-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemycardtheme',
            name='enemy',
        ),
        migrations.RemoveField(
            model_name='enemycardtheme',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='partnercardtheme',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnercardtheme',
            name='theme',
        ),
        migrations.DeleteModel(
            name='CharacterCardTheme',
        ),
        migrations.DeleteModel(
            name='EnemyCardTheme',
        ),
        migrations.DeleteModel(
            name='PartnerCardTheme',
        ),
    ]
