# Generated by Django 6.0.1 on 2026-03-28 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('buff_hp', models.IntegerField(default=0)),
                ('buff_atk', models.IntegerField(default=0)),
                ('buff_def', models.IntegerField(default=0)),
                ('debuff_hp', models.IntegerField(default=0)),
                ('debuff_atk', models.IntegerField(default=0)),
                ('debuff_def', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('INFO', 'INFO'), ('ATTACK', 'ATTACK'), ('DEFEND', 'DEFEND'), ('HEAL', 'HEAL'), ('SEARCH', 'SEARCH')], default='INFO')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Finished', 'Finished')], default='Active', max_length=20)),
                ('turns', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('buff_hp', models.IntegerField(default=0)),
                ('buff_atk', models.IntegerField(default=0)),
                ('buff_def', models.IntegerField(default=0)),
                ('debuff_hp', models.IntegerField(default=0)),
                ('debuff_atk', models.IntegerField(default=0)),
                ('debuff_def', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
