# Generated by Django 6.0.1 on 2026-02-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0006_alter_character_attack_alter_character_defense_and_more'),
        ('enemies', '0003_alter_enemy_attack_alter_enemy_defense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Finished', 'Finished')], default='Active', max_length=20)),
                ('turns', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('current_hp', models.IntegerField()),
                ('current_atk', models.IntegerField()),
                ('current_def', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('current_hp', models.IntegerField()),
                ('current_atk', models.IntegerField()),
                ('current_def', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemies.enemy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
