# Generated by Django 6.0.1 on 2026-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlecharacter',
            name='buff_atk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='buff_def',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='buff_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='debuff_atk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='debuff_def',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='debuff_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='buff_atk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='buff_def',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='buff_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='debuff_atk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='debuff_def',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='debuff_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
