# Generated by Django 6.0.1 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
        migrations.AddField(
            model_name='battleenemy',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle'),
        ),
    ]
