# Generated by Django 6.0.1 on 2026-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0002_initial'),
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleenemy',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemies.enemy'),
        ),
        migrations.AddField(
            model_name='battlelog',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlelogs', to='battle.battle'),
        ),
    ]
