# Generated by Django 6.0.1 on 2026-02-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_pedro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedro',
        ),
    ]
