# Generated by Django 6.0.1 on 2026-02-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_battlepedro'),
        ('characters', '0006_alter_character_attack_alter_character_defense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('buff_hp', models.IntegerField(blank=True, default=0)),
                ('buff_atk', models.IntegerField(blank=True, default=0)),
                ('buff_def', models.IntegerField(blank=True, default=0)),
                ('debuff_hp', models.IntegerField(blank=True, default=0)),
                ('debuff_atk', models.IntegerField(blank=True, default=0)),
                ('debuff_def', models.IntegerField(blank=True, default=0)),
                ('current_hp', models.IntegerField(blank=True)),
                ('current_atk', models.IntegerField(blank=True)),
                ('current_def', models.IntegerField(blank=True)),
                ('is_alive', models.BooleanField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BattlePedro',
        ),
    ]
