# Generated by Django 6.0.1 on 2026-02-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_battlechar_delete_battlepedro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlecharacter',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='battlecharacter',
            name='character',
        ),
        migrations.RemoveField(
            model_name='battleenemy',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='battleenemy',
            name='enemy',
        ),
        migrations.DeleteModel(
            name='BattleChar',
        ),
        migrations.DeleteModel(
            name='BattleCharacter',
        ),
        migrations.DeleteModel(
            name='BattleEnemy',
        ),
    ]
