# Generated by Django 6.0.1 on 2026-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_battlecharacter_battleenemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlecharacter',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
