# Generated by Django 6.0.1 on 2026-02-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_alter_battlecharacter_is_alive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlecharacter',
            name='current_atk',
        ),
        migrations.RemoveField(
            model_name='battlecharacter',
            name='current_def',
        ),
        migrations.RemoveField(
            model_name='battlecharacter',
            name='is_alive',
        ),
        migrations.RemoveField(
            model_name='battleenemy',
            name='current_atk',
        ),
        migrations.RemoveField(
            model_name='battleenemy',
            name='current_def',
        ),
        migrations.RemoveField(
            model_name='battleenemy',
            name='is_alive',
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='buff_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='buff_def',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='buff_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='current_hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='debuff_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='debuff_def',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battlecharacter',
            name='debuff_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='buff_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='buff_def',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='buff_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='current_hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='debuff_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='debuff_def',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battleenemy',
            name='debuff_hp',
            field=models.IntegerField(default=0),
        ),
    ]
