# Generated by Django 6.0.1 on 2026-02-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_alter_battle_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='turns',
            field=models.IntegerField(default=1),
        ),
    ]
