# Generated by Django 6.0.1 on 2026-02-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0012_alter_battle_turns'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlelogs', to='battle.battle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
