# Generated by Django 6.0.1 on 2026-02-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_battlelogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattleLogs',
            new_name='BattleLog',
        ),
    ]
