# Generated by Django 6.0.1 on 2026-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0014_rename_battlelogs_battlelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlelog',
            name='log_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlelog',
            name='content',
            field=models.TextField(),
        ),
    ]
