# Generated by Django 6.0.1 on 2026-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0015_battlelog_log_type_alter_battlelog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlelog',
            name='log_type',
            field=models.CharField(choices=[('INFO', 'INFO'), ('ATTACK', 'ATTACK'), ('DEFEND', 'DEFEND'), ('HEAL', 'HEAL'), ('SEARCH', 'SEARCH')], default='INFO'),
        ),
    ]
